services:
  db:
    image: mysql:8.0
    env_file:
      - .env.dbase
    environment:
      TZ: ${TZ:-Europe/Oslo}
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-time-zone=${TZ:-Europe/Oslo}
      --skip-log-bin
    ports:
      - "${MYSQL_PORT_HOST:-3309}:3306"
    volumes:
      - movies_dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dbase
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Server=db;Port=3306;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};SslMode=None"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  dev:
    image: nixos/nix:2.22.1
    container_name: cs_oppgave_05-nix-dev
    working_dir: /work
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    volumes:
      - .:/work
      - nix-store:/nix
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "bash","-lc","git config --global --add safe.directory /work || true; exec sleep infinity" ]

volumes:
  movies_dbdata: {}
  nix-store: {}

# Validation: docker compose config